# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2bc5ae0ffd18b346ab44704a55f1371c0f229a3d5ce857ec5d012824f717d8879b032ce374f1d823d2ddf7d24608423844ce52a422d928312f545e5324bdb71c

test:
  secret_key_base: a7e08433f59890b4ddf66228d9334a9759783dbf63478d1ff2cbef846f4a40d9681bfda3b3aa4b08e3595cd8f73377f165e4df75e27d8c00c01e2cd17248e84a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
